### ISSUE TITLE
Problem with bower+git install

### ISSUE THREAD

**Issue by korto** [2fd/jspm-bower-endpoint#25]
I am trying to install a bower package using the command below: 

```jspm install name=bower:git@github.com:alangrafu/radar-chart-d3.git```

but I am getting this error: ```Repo bower:git not found!```

Any clues?

**Comment by korto** [comment]
My bad, closing this one.

**Comment by juriejan** [comment]
I'm having this issue too. What was the solution?

**Comment by jonricaurte** [comment]
I'm getting the same issue. @juriejan @2fd

**Comment by jonricaurte** [comment]
I am using 0.17 if that makes a difference.
